  robot:
    update_rate: 50

  canvas:
    position: [0.6, 0.0, 0.05]
    physical_size: 0.4
    pixel_width: 800
    pixel_height: 600
    contact_height: 0.02
    safe_height: 0.05

  pen:
    length: 0.12

  drawing:
    circle_center: [400, 300]
    circle_radius: 80
    segments: 24

  movement:
    interpolation_steps: 10